name: workflow-maven-deploy

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout.
        uses: actions/checkout@v2

      - name: Step 2 - Setup Java.
        uses: drewctaylor/setup-java@actions-setup-java-85-b
        with:
          java-version: 11
          server-id-list: require, type-encoded, github
          server-username: SERVER_USERNAME
          server-password: SERVER_PASSWORD

      - name: Step 3 - Maven Deploy.
        run: mvn -B deploy
        env:
          SERVER_USERNAME: ${{ github.actor }}
          SERVER_PASSWORD: ${{ github.token }}
